# Generated by Django 3.1.3 on 2020-11-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='poduct_image',
            new_name='product_image',
        ),
    ]
